# Generated by Django 5.1.1 on 2024-09-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="kassa_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
